spring:
   profiles:
     active: -dev

---
spring: 
   profiles: dev   #开发环境
   application: 
      name: eureka-7002
server:
    port: 7002
eureka:
   client:
      service-url:
          defaultZone: http://eureka7001:7001/eureka/
---
spring:
   profiles: test    #测试环境
   application: 
      name: eureka-7002
server:
    port: 70022
eureka:
   client:
      service-url:
         defaultZone: http://eureka7001:7001/eureka/