spring:
   profiles:
     active: -dev

---
spring: 
   profiles: dev   #开发环境
   application: 
      name: eureka-7001
server:
    port: 7001
eureka:
   client:
      service-url:
          defaultZone: http://eureka7002:7002/eureka/
---
spring:
   profiles: test    #测试环境
   application: 
      name: eureka-7001
server:
    port: 70011
eureka:
   client:
      service-url:
         defaultZone: http://eureka7002:7002/eureka/